# Generated by Django 4.2.30 on 2026-06-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_parent_id', models.IntegerField(blank=True, null=True)),
                ('account_mode', models.CharField(choices=[('header', 'Header'), ('detail', 'Detail')], default='header', max_length=20)),
                ('account_classification', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income')], default='asset', max_length=50)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('bank', 'Bank'), ('accounts_receivable', 'Accounts Receivable'), ('other_current_asset', 'Other Current Asset'), ('fixed_asset', 'Fixed Asset'), ('other_asset', 'Other Asset'), ('liability', 'Liability'), ('credit_card', 'Credit Card'), ('accounts_payable', 'Accounts Payable'), ('long_term_liability', 'Long Term Liability'), ('other_liability', 'Other Liability'), ('equity', 'Equity'), ('income', 'Income'), ('cost_of_sales', 'Cost of Sales'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], default='asset', max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('account_currency', models.CharField(max_length=4)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax_code', models.CharField(choices=[('N-T', 'N-T'), ('T', 'T')], default='N-T', max_length=50)),
                ('account_level', models.IntegerField(default=1)),
                ('account_hierarchy', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('account_note', models.TextField(blank=True, null=True)),
                ('show_on_dashboard', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
