# Generated by Django 4.2.30 on 2026-06-12 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('psp_banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconcile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reconcile_date', models.DateField()),
                ('viewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('psp_balance_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amentments', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('psp_opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('psp_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account')),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
                ('psp_bank_id', models.ForeignKey(db_column='psp_bank_id', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_banks.pspbank')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconcile_data',
            },
        ),
        migrations.CreateModel(
            name='ReconcileTransactionLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reconcile_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('old_transaction', models.JSONField(blank=True, null=True)),
                ('updated_transaction', models.JSONField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('MODIFIED_TRANSACTION_ATLAS', 'MODIFIED_TRANSACTION_ATLAS'), ('MODIFIED_TRANSACTION_PSP', 'MODIFIED_TRANSACTION_PSP'), ('ADDED_TRANSACTION_UNREC_ATLAS', 'ADDED_TRANSACTION_UNREC_ATLAS'), ('ADDED_TRANSACTION_UNREC_PSP', 'ADDED_TRANSACTION_UNREC_PSP'), ('MODIFIED_TRANSACTION_UNREC_ATLAS', 'MODIFIED_TRANSACTION_UNREC_ATLAS'), ('MODIFIED_TRANSACTION_UNREC_PSP', 'MODIFIED_TRANSACTION_UNREC_PSP'), ('MOVED_TRANSACTION_UNREC_ATLAS', 'MOVED_TRANSACTION_UNREC_ATLAS'), ('MOVED_TRANSACTION_UNREC_PSP', 'MOVED_TRANSACTION_UNREC_PSP'), ('ADDED_TRANSACTION_ATLAS', 'ADDED_TRANSACTION_ATLAS'), ('DELETED_TRANSACTION_ATLAS', 'DELETED_TRANSACTION_ATLAS'), ('DELETED_TRANSACTION_PSP', 'DELETED_TRANSACTION_PSP'), ('MODIFIED_OPENING_CLOSING_BALANCE_PSP', 'MODIFIED_OPENING_CLOSING_BALANCE_PSP')], max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('psp_bank_id', models.ForeignKey(db_column='psp_bank_id', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_banks.pspbank')),
                ('reconcile_id', models.ForeignKey(blank=True, db_column='reconcile_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reconciliation.reconcile')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconcile_transaction_logs',
            },
        ),
    ]
