# Generated by Django 4.2.30 on 2026-06-12 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refrence_number', models.CharField(default='', max_length=20)),
                ('transaction_number', models.CharField(default='', max_length=100)),
                ('reconcile_mapping_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('mapping_hash_date', models.DateField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(default='AUD', max_length=4)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('qty', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('transaction_source', models.CharField(default='manual', max_length=255)),
                ('transaction_date', models.DateField()),
                ('aged_date', models.DateField(blank=True, null=True)),
                ('transaction_datetime', models.DateTimeField(blank=True, null=True)),
                ('invoice_source_id', models.IntegerField(blank=True, null=True)),
                ('invoice_source_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_invoice_transaction', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('is_flagged_transaction', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('is_reconcile_amended', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('is_cut_off', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('cut_off_date', models.DateTimeField(blank=True, null=True)),
                ('cut_off_comment', models.TextField(blank=True, null=True)),
                ('is_reverse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
