# Generated by Django 4.2.30 on 2026-06-11 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ManyToManyField(blank=True, db_table='companies_users', related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
