"""
Django settings for atlas project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECRET_KEY: read from env in Docker/prod, fall back to the dev key locally.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-u#$cs803ab%+@ic78w^%k)@02xyxysy1(5_(@5=qer#4-*+k6-',
)

# DEBUG: defaults to True for local dev; set DJANGO_DEBUG=0 to disable.
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# Comma-separated list, e.g. "localhost,127.0.0.1,atlas.example.com"
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'atlasdemo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files in production (just below SecurityMiddleware
    # per its docs). Harmless in dev with DEBUG=True (Django serves them anyway).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'atlas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atlas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# MySQL. All connection details come from environment variables so local dev
# and Docker can point at different servers without code changes.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':     os.environ.get('DJANGO_DB_NAME',     'atlas'),
        'USER':     os.environ.get('DJANGO_DB_USER',     'atlas'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', 'atlas'),
        'HOST':     os.environ.get('DJANGO_DB_HOST',     '127.0.0.1'),
        'PORT':     os.environ.get('DJANGO_DB_PORT',     '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Where `collectstatic` writes static files for gunicorn to serve.
# Only matters in Docker / production; harmless locally.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Tell WhiteNoise to compress + fingerprint static files (admin CSS, etc.).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirects: where Django sends users on login/logout, and which URL
# the @login_required decorator redirects unauthenticated users to.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'compare'
LOGOUT_REDIRECT_URL = 'login'

# Where uploaded Excel/CSV files are stored on disk while being compared.
# Env-driven so Docker can point this at a shared volume both web and worker mount.
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', str(BASE_DIR / 'media'))
MEDIA_URL = 'media/'

# Celery: broker is where tasks are queued; result backend is where return values land.
# Local default: assumes redis is running on 127.0.0.1:6379 (the Docker `redis` service
# port-forwards there). Override DJANGO_REDIS_URL to point elsewhere.
CELERY_BROKER_URL = os.environ.get('DJANGO_REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('DJANGO_REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
# Don't let one slow comparison hang forever.
CELERY_TASK_TIME_LIMIT = 600       # hard kill after 10 min
CELERY_TASK_SOFT_TIME_LIMIT = 540  # raise SoftTimeLimitExceeded at 9 min

# Max upload size 10MB (Django default is 2.5MB which is small for Excel).
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
