# Generated by Django 4.2.30 on 2026-06-12 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PspBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_filters', models.JSONField(blank=True, null=True)),
                ('credit_column_rules', models.JSONField(blank=True, null=True)),
                ('debit_column_rules', models.JSONField(blank=True, null=True)),
                ('attribute_mapping', models.JSONField()),
                ('matching_rules', models.JSONField()),
                ('psp_data_schema', models.JSONField()),
                ('cut_off_time', models.TimeField(blank=True, default='23:59:59', null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('psp_reserve_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account')),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
            ],
            options={
                'db_table': 'psp_banks',
                'unique_together': {('name', 'company_id')},
            },
        ),
        migrations.CreateModel(
            name='PspTransactionsBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_records', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=200)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_file_name', models.CharField(default='', max_length=255)),
                ('is_deleted', models.IntegerField(default=0)),
                ('psp_bank_id', models.ForeignKey(db_column='psp_bank_id', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_banks.pspbank')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psp_transactions_batch',
            },
        ),
        migrations.CreateModel(
            name='PspCustomers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
            ],
            options={
                'db_table': 'psp_customers',
            },
        ),
    ]
